# Required metadata
sonar.projectKey=muhammadtouseef11222211_cyberwithspider
sonar.projectName=CyberWithSpider
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=src

# SonarCloud URL (cloud-based SonarQube)
sonar.host.url=https://sonarcloud.io

# Authentication Token
sonar.login=1a04e5067514a4bbdc3c781f8bc4e0c328d1cb5b

